2 add footer
specollective/spec-frontend pull request #22
Opened 2023-04-18 05:02 UTC by kingkai1990

## Ticket Description
<-- Copy and paste or write the tickets description here-->
<img width="1031" alt="Screenshot 2023-04-17 at 10 01 31 PM" src="https://user-images.githubusercontent.com/43101229/232675887-25768eb5-114a-46bb-896f-045768984623.png">

Add footer according to spec 
## Description of Changes
<-- Brief description of the changes you made, files you touched, etc -->

## Before and After for UI Updates
<-- You should have 2 images minimum, for desktop, 4 for mobile and desktop combined -->

Before:
![Screenshot 2023-04-12 at 12 30 36 PM](https://user-images.githubusercontent.com/43101229/232675551-60bafced-9f03-4738-b424-5682df05df44.png)

After
<img wid
<img width="1254" alt="Screenshot 2023-04-17 at 6 37 04 PM" src="https://user-images.githubusercontent.com/43101229/232675508-ce564edb-2513-4c6b-9541-e3e930ad2e20.png">
th="685" alt="Screenshot 2023-04-17 at 9 58 05 PM" src="https://user-images.githubusercont
<img width="337" alt="Screenshot 2023-04-17 at 9 57 33 PM" src="https://user-images.githubusercontent.com/43101229/232675487-59ef59ac-5721-47df-a41c-1fb657045f81.png">
ent.com/43101229/232675445-6980a9ec-e953-4679-a340-b4acd5850995.png">
:

## For PR Reviewer
- [ ] Does this file change the yarn.lock, package.json or package-lock.json file? If so, why?
- [ ] If this pr contains mobile and desktop changes, did you test on IphoneXr and desktop views?
- [ ] Does this file match the related tickets linked figma file, or does it pass the visual smell test?
- [ ] If this file contains javascript, does the javascript pass the smell test?
- [ ] If you don't feel super confident in your review, did you assign someone more senior to double check?

2023-04-18 21:04 UTC, najwanan commented on pages/spect2.tsx
Looks like this might be a duplicate of index.tsx? Can we remove this?

2023-04-18 21:08 UTC, najwanan commented on .hintrc
I think this is a file from some sort of utility you're using to help with code hints. Great that you found this, hope it's helping. Let's pull it out of your PR. You can do this by adding this file name ".hintrc" to .gitignore. That way it won't get pushed up to the remote branch.

2023-04-18 21:12 UTC, najwanan requested changes
@khiryshank it looks like there are currently some merge conflicts. Before tackling those, I'd suggest the following. 
Pull down the latest changes from main, with the new home page and file structure. 
Rearrange your components (move your footer file into components and then import your footer file into home.tsx) 
Get rid of any extraneous files, like the .hintrc or spect2.tsx

Then once all those changes are pushed up, see if there's still merge conflicts

2023-04-18 21:21 UTC, khiryshank commented
Kk, will do so and complete it around 6:30 PST

2023-04-19 21:08 UTC, khiryshank commented
I'm no longer seeing the merge conflicts, hoping I resolved everything

2023-04-19 21:47 UTC, najwanan commented on components/Footer.tsx
> +            {/* <div className='flex-col bg-yellow-600 max-w-3xl mx-auto'> */}
Let's pull these out if not needed.

2023-04-19 21:47 UTC, najwanan commented on components/Footer.tsx
> +              {/* </div>   */}
Same here, delete if not needed or in use

2023-04-19 21:53 UTC, najwanan reviewed
So close! There's a slight deviation right now from the mobile design and that is that it's missing the social links. There are a few approaches to handle this. You could create a seperate mobile nav social component and hide it as necessary. 

I'm actually okay with merging in as (once we delete out the extra commented out lines), knowing that we'll have a follow-up ticket to finalize mobile. 
 
<img width="180" alt="Screenshot 2023-04-19 at 2 49 20 PM" src="https://user-images.githubusercontent.com/66931010/233207787-a396a843-3c53-4a52-b551-f0a09060f805.png">

2023-04-20 15:15 UTC, najwanan approved these changes
Looks good to me!

2023-04-20 15:40 UTC, merged